users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('user_details/<int:user_id>/', views.user_details, name='user_details'),
    path('personal_office/', views.personal_office, name='personal_office'),
    path('update_user_info/<int:user_id>/', views.update_user_details, name='update_user_info'),
    path('check-email/', views.check_email, name='check_email'),
]

vibefit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from users import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('workouts/', include('workouts.urls')),
    path('nutrition/', include('nutrition.urls')),
    path('users/', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/models.py
from django.db import models
from django.contrib.auth.models import User

class UserDetails(models.Model):
    GENDER_CHOICES = [
        ('male', 'Male'),
        ('female', 'Female'),
    ]
    
    user = models.OneToOneField(User, on_delete=models.CASCADE, unique=True, null=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    height = models.IntegerField()
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    goal_choices = [
        ('lose-weight', 'Lose Weight'),
        ('gain-muscle', 'Gain Muscle'),
        ('maintain', 'Maintain Weight'),
    ]
    goal = models.CharField(max_length=50, choices=goal_choices)
    training_level_choices = [
        ('beginner', 'Beginner'),
        ('intermediate', 'Intermediate'),
        ('advanced', 'Advanced'),
    ]
    training_level = models.CharField(max_length=50, choices=training_level_choices)
    avatar = models.ImageField(upload_to='avatars/', default='avatars/default_avatar.png', blank=True, null=True)
    birth_date = models.DateField(null=True)
    
    class Meta:
        verbose_name = 'user information'
        verbose_name_plural = 'user information'

    def __str__(self):
        return self.user.username


class WeightRecord(models.Model):
    user = models.ForeignKey(UserDetails, on_delete=models.CASCADE)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateField()

    def __str__(self):
        return f"{self.user.user.username} - {self.date} - {self.weight} kg"

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    height = models.PositiveIntegerField(default=150)
    weight = models.DecimalField(max_digits=5, decimal_places=2)
    goal = models.CharField(max_length=50, choices=[
        ('Lose Weight', 'Lose Weight'),
        ('Gain Muscle', 'Gain Muscle'),
        ('Maintain', 'Maintain Weight')
    ], default='Maintain')
    training_level = models.CharField(max_length=50, choices=[
        ('Beginner', 'Beginner'),
        ('Int ermediate', 'Intermediate'),
        ('Advanced', 'Advanced')
    ], default='Beginner')
    avatar = models.ImageField(upload_to='avatars/', null=True, blank=True)

    def __str__(self):
        return self.user.username

users/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import UserDetails
from django.contrib.auth import authenticate, login
from django.core.exceptions import ValidationError
from datetime import datetime
from decimal import Decimal
import re

class CustomUserCreationForm(forms.ModelForm):
    email = forms.EmailField(
        label="",
        widget=forms.EmailInput(attrs={"placeholder": "Email"})
    )
    username = forms.CharField(
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Username"})
    )
    password = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={"placeholder": "Password"})
    )
    password2 = forms.CharField(
        label="",
        widget=forms.PasswordInput(attrs={"placeholder": "Confirm Password"})
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email

    def clean_password(self):
        password = self.cleaned_data.get("password")
        if len(password) < 8:
            raise forms.ValidationError("Password must be at least 8 characters long.")
        if not re.search(r'\d', password):
            raise forms.ValidationError("Password must contain at least one number.")
        return password

    def clean(self):
        cleaned_data = super().clean()
        password = cleaned_data.get("password")
        password2 = cleaned_data.get("password2")

        if password != password2:
            raise forms.ValidationError("Passwords do not match.")
        return cleaned_data

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
            UserDetails.objects.create(
                user=user,
                height=170,
                weight=70,
                goal='maintain',
                training_level='beginner'
            )
        return user
    
def validate_decimal(value):
    try:
        Decimal(value)
    except:
        raise ValidationError("Invalid decimal value")

class UserDetailsForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Если пол уже установлен, делаем поле readonly
        if self.instance and self.instance.gender:
            self.fields['gender'].widget.attrs['readonly'] = True
            self.fields['gender'].widget.attrs['disabled'] = True
    
    class Meta:
        model = UserDetails
        fields = ['gender', 'height', 'weight', 'goal', 'training_level', 'birth_date']
        widgets = {
            'gender': forms.Select(choices=UserDetails.GENDER_CHOICES),
            'height': forms.NumberInput(attrs={'placeholder': 'Height (cm)'}),
            'goal': forms.Select(attrs={'placeholder': 'Goal'}),
            'training_level': forms.Select(attrs={'placeholder': 'Training level'}),
            'birth_date': forms.DateInput(attrs={'type': 'date', 'placeholder': 'Birth date'}),
        }

    def clean_birth_date(self):
        birth_date = self.cleaned_data.get('birth_date')
        today = datetime.today()
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))
        
        if age < 18:
            raise ValidationError("You must be at least 18 years old.")
        return birth_date

class LoginForm(forms.Form):
    email = forms.EmailField(
        label='',
        max_length=254,
        widget=forms.EmailInput(attrs={'placeholder': 'Email'})
    )
    password = forms.CharField(
        label='',
        widget=forms.PasswordInput(attrs={'placeholder': 'Password'})
    )

    def clean(self):
        cleaned_data = super().clean()
        email = cleaned_data.get('email')
        password = cleaned_data.get('password')

        if email and password:
            try:
                user = User.objects.get(email=email)
            except User.DoesNotExist:
                raise forms.ValidationError("No user with this email was found.")
            
            user = authenticate(username=user.username, password=password)
            if user is None:
                raise forms.ValidationError("Invalid email or password.")

        return cleaned_data

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, authenticate
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from .forms import UserDetailsForm
from django.contrib.auth.models import User
from datetime import datetime
from .forms import LoginForm
from .models import UserDetails, WeightRecord
from .forms import CustomUserCreationForm
from django.http import JsonResponse
from decimal import Decimal

def main(request):
    return render(request, 'main.html')

def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()

            user_details, created = UserDetails.objects.get_or_create(
                user=user,
                defaults={
                    'height': 170,
                    'weight': 70,
                    'goal': 'maintain',
                    'training_level': 'beginner',
                    'birth_date': '2000-01-01'
                }
            )

            return redirect('user_details', user_id=user.id)
    else:
        form = CustomUserCreationForm()
    
    return render(request, 'registration.html', {'form': form})

def check_email(request):
    email = request.GET.get('email', None)
    print(f"Checking email: {email}")
    if email and User.objects.filter(email=email).exists():
        return JsonResponse({'error': 'This email already in use.'})
    return JsonResponse({'success': True})


def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            try:
                user = User.objects.get(email=email)
                user = authenticate(request, username=user.username, password=password)
                if user is not None:
                    login(request, user)
                    return redirect('personal_office')
                else:
                    form.add_error(None, "Invalid email or password.")
            except User.DoesNotExist:
                form.add_error('email', "No user found with this email.")
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form})

def user_details(request, user_id):
    user = get_object_or_404(User, id=user_id)
    
    try:
        user_details = UserDetails.objects.get(user=user)
    except UserDetails.DoesNotExist:
        user_details = UserDetails.objects.create(
            user=user,
            height=170,
            weight=70,
            goal='maintain',
            training_level='beginner'
        )

    if request.method == 'POST':
        form = UserDetailsForm(request.POST, request.FILES, instance=user_details)
        if form.is_valid():
            # Если пол уже был установлен, сохраняем исходное значение
            if user_details.gender:
                details = form.save(commit=False)
                details.gender = user_details.gender
                details.save()
            else:
                form.save()
            
            user.backend = 'users.backend.EmailAuthBackend'
            login(request, user)
            return redirect('login')
    else:
        form = UserDetailsForm(instance=user_details)

    return render(request, 'user_details.html', {'form': form, 'user_details': user_details})


def calculate_age(birth_date):
    today = datetime.today()
    return today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))

@login_required
def personal_office(request):
    user_details = get_object_or_404(UserDetails, user=request.user)
    weight_records = WeightRecord.objects.filter(user=user_details).order_by('date')
    birth_date = user_details.birth_date
    age = calculate_age(birth_date)
    labels = [record.date.strftime('%Y-%m-%d') for record in weight_records]
    weights = [float(record.weight) for record in weight_records]
    context = {
        'user_details': user_details,
        'labels': labels,
        'weights': weights,
        'age': age,
    }
    return render(request, 'personal_office.html', context)

@login_required
def update_user_details(request, user_id):
    user_details = get_object_or_404(UserDetails, user__id=user_id)
    if request.method == 'POST':
        new_weight = request.POST.get('weight')
        if new_weight:
            new_weight = Decimal(new_weight)

        new_height = request.POST.get('height')
        new_goal = request.POST.get('goal')
        new_training_level = request.POST.get('training_level')
        new_avatar = request.FILES.get('avatar')

        user_details.height = new_height
        user_details.weight = new_weight
        user_details.goal = new_goal
        user_details.training_level = new_training_level

        if new_avatar:
            user_details.avatar = new_avatar

        user_details.save()

        WeightRecord.objects.create(
            user=user_details,
            weight=new_weight,
            date=timezone.now().date()
        )

        return redirect('personal_office')
    
    weight_records = WeightRecord.objects.filter(user=user_details).order_by('date')
    labels = [record.date.strftime('%Y-%m-%d') for record in weight_records]
    weights = [record.weight for record in weight_records]

    return render(request, 'users/personal_office.html', {
        'user_details': user_details,
        'labels': labels,
        'weights': weights
    })

users/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Login Page</title>
    <link rel="stylesheet" href="{% static 'css/registration.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo&display=swap"
      rel="stylesheet"
    />
    <style>
      .error-messages {
        margin-top: 10px;
        color: red;
        font-size: 14px;
      }
      .form-errors {
        background-color: #ffe6e6;
        border: 1px solid #ffcccc;
        color: #990000;
        padding: 10px;
        margin-bottom: 15px;
        border-radius: 5px;
      }
      .password-field {
        position: relative;
      }
      .toggle-password {
        position: absolute;
        top: 50%;
        right: 10px;
        transform: translateY(-50%);
        background: none;
        border: none;
        cursor: pointer;
        color: #007bff;
        font-size: 16px;
      }
    </style>
  </head>
  <body>
    <div class="page-container">
      <div class="registration-container">
        <div class="registration-image">
          <img
            src="{% static 'img/registration.jpg' %}"
            alt="Registration Image"
          />
        </div>
        <div class="form-container">
          <h1>Login</h1>
          {% if form.non_field_errors %}
          <div class="form-errors">
            {% for error in form.non_field_errors %}
            <p>{{ error }}</p>
            {% endfor %}
          </div>
          {% endif %}
          <form method="post">
            {% csrf_token %} {% for field in form %}
            <div class="form-field">
              <label for="{{ field.id_for_label }}">{{ field.label }}</label>
              {% if field.name == "password" %}
              <div class="password-field">{{ field }}</div>
              {% else %} {{ field }} {% endif %} {% if field.errors %}
              <div class="error-messages">
                {% for error in field.errors %}
                <p class="error">{{ error }}</p>
                {% endfor %}
              </div>
              {% endif %}
            </div>
            {% endfor %}
            <button class="cta-button" type="submit">Login</button>
          </form>

          <p>
            Don't have an account? <a href="{% url 'register' %}">Sign Up</a>
          </p>
        </div>
      </div>
    </div>
  </body>
</html>

users/templates/personal_office.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Personal Office</title>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    <link rel="stylesheet" href="{% static 'css/personal_office.css' %}" />
    <style>
      .modal {
        display: none;
        position: fixed;
        z-index: 1;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        background-color: rgba(0, 0, 0, 0.4);
        justify-content: center;
        align-items: center;
      }

      .modal-content {
        background-color: #fefefe;
        margin: 15% auto;
        padding: 20px;
        border: 1px solid #888;
        width: 80%;
        max-width: 500px;
        box-shadow: 0 4px 8px rgba(0, 0, 0, 0.2);
        border-radius: 10px;
        animation: fadeIn 0.3s ease;
        position: relative;
      }

      .close-btn {
        color: #aaa;
        font-size: 28px;
        font-weight: bold;
        position: absolute;
        top: 10px;
        right: 20px;
        cursor: pointer;
      }

      .close-btn:hover,
      .close-btn:focus {
        color: black;
        text-decoration: none;
      }

      @keyframes fadeIn {
        from {
          opacity: 0;
        }
        to {
          opacity: 1;
        }
      }

      .avatar-container img {
        width: 150px;
        height: 150px;
        border-radius: 50%;
        object-fit: cover;
      }
    </style>
  </head>
  <body>
    {% include 'components/header.html' %}

    <div class="container">
      <div class="card">
        <div class="avatar-container">
          <img src="{% if user_details.avatar %}{{ user_details.avatar.url }}{% else %}{% static 'images/placeholder.png' %}{% endif %}" alt="User Avatar" />
        </div>
        <div class="details">
          <h2 class="user">
            <strong>{{ user_details.user.username }}</strong>
          </h2>
          <p><strong>Gender:</strong> {{ user_details.get_gender_display }}</p>
          <p><strong>Height:</strong> {{ user_details.height }} cm</p>
          <p><strong>Weight:</strong> {{ user_details.weight }} kg</p>
          <p><strong>Age:</strong> {{ age }}</p>
          <p><strong>Goal:</strong> {{ user_details.get_goal_display }}</p>
          <p><strong>Training level:</strong> {{ user_details.get_training_level_display }}</p>
          <button class="edit-btn" id="editBtn">Edit</button>
        </div>
      </div>

      <div class="chart-container">
        <h2 style="text-align: center">Weight Graph</h2>
        <canvas id="weightChart"></canvas>
      </div>
    </div>

    <div id="editModal" class="modal">
      <div class="modal-content">
        <span class="close-btn" id="closeBtn">&times;</span>
        <h2>Edit your details</h2>
        <form
          method="POST"
          action="{% url 'update_user_info' user_details.user.id %}"
          enctype="multipart/form-data"
        >
          {% csrf_token %}
          <div class="form-group">
            <label for="id_height">Height (cm):</label>
            <input
              type="number"
              name="height"
              value="{{ user_details.height }}"
              required
            />
          </div>
          <div class="form-group">
            <label for="id_weight">Weight (kg):</label>
            <input
              type="number"
              name="weight"
              value="{{ user_details.weight }}"
              step="0.01"
              required
            />
          </div>
          <div class="form-group">
            <label for="id_goal">Goal:</label>
            <select name="goal" id="id_goal" required>
              <option value="lose-weight" {% if user_details.goal == "lose-weight" %}selected{% endif %}>
                Lose Weight
              </option>
              <option value="maintain" {% if user_details.goal == "maintain" %}selected{% endif %}>
                Maintain Weight
              </option>
              <option value="gain-muscle" {% if user_details.goal == "gain-muscle" %}selected{% endif %}>
                Gain Muscle
              </option>
            </select>
          </div>
          <div class="form-group">
            <label for="id_training_level">Training level:</label>
            <select name="training_level" id="id_training_level" required>
              <option value="beginner" {% if user_details.training_level == "beginner" %}selected{% endif %}>
                Beginner
              </option>
              <option value="intermediate" {% if user_details.training_level == "intermediate" %}selected{% endif %}>
                Intermediate
              </option>
              <option value="advanced" {% if user_details.training_level == "advanced" %}selected{% endif %}>
                Advanced
              </option>
            </select>
          </div>
          <div class="form-group">
            <label for="id_avatar">Avatar:</label>
            <input type="file" name="avatar" />
          </div>
          <button type="submit" class="save-btn">Save changes</button>
        </form>
      </div>
    </div>

    {% include 'components/footer.html' %}
    
    <script>
      const editBtn = document.getElementById('editBtn');
      const modal = document.getElementById('editModal');
      const closeBtn = document.getElementById('closeBtn');

      editBtn.onclick = function () {
        modal.style.display = 'flex';
      };

      closeBtn.onclick = function () {
        modal.style.display = 'none';
      };

      window.onclick = function (event) {
        if (event.target === modal) {
          modal.style.display = 'none';
        }
      };

      const ctx = document.getElementById('weightChart').getContext('2d');
      const weightChart = new Chart(ctx, {
        type: 'line',
        data: {
          labels: {{ labels|safe }},
          datasets: [
            {
              label: 'Weight (kg)',
              data: {{ weights|safe }},
              borderColor: '#9b957e',
              backgroundColor: 'rgba(155, 149, 126, 0.2)',
              borderWidth: 2,
              fill: true,
              pointRadius: 5,
              pointBackgroundColor: '#9b957e',
            },
          ],
        },
        options: {
          responsive: true,
          plugins: {
            legend: {
              display: true,
              position: 'top',
              labels: {
                color: '#333',
              },
            },
          },
          scales: {
            x: {
              grid: { display: false },
              ticks: { display: false },
            },
            y: {
              beginAtZero: false,
              grid: { color: '#ddd' },
              ticks: { color: '#333' },
            },
          },
        },
      });
    </script>
  </body>
</html>

users/templates/registration.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Registration Page</title>
    <link rel="stylesheet" href="{% static 'css/registration.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <div class="page-container">
      <div class="registration-container">
        <div class="registration-image">
          <img
            src="{% static 'img/registration.jpg' %}"
            alt="Registration Image"
          />
        </div>
        <div class="form-container">
          <h1>Build Your Perfect Body</h1>

          <form method="post" id="registrationForm">
            {% csrf_token %} {% for field in form %}
            <div class="form-field">
              {% if field.name == "password" or field.name == "password2" %}
              <div class="password-field">{{ field }}</div>
              {% else %} {{ field }} {% endif %}
              <div class="error-messages" id="error-{{ field.name }}"></div>
            </div>
            {% endfor %}

            <button class="cta-button" type="submit">Sign Up</button>
          </form>

          <p>Already have an account? <a href="{% url 'login' %}">Log in</a></p>
        </div>
      </div>
    </div>

    <div id="toast" class="hidden"></div>

    <script>
      function togglePassword(element) {
        const input = element.previousElementSibling;
        input.type = input.type === "password" ? "text" : "password";
      }

      document.addEventListener("DOMContentLoaded", function () {
        const emailInput = document.querySelector('input[name="email"]');
        const password1 = document.querySelector('input[name="password"]');
        const password2 = document.querySelector('input[name="password2"]');
        const form = document.getElementById("registrationForm");

        function showError(fieldName, message) {
          const errorDiv = document.getElementById("error-" + fieldName);
          errorDiv.textContent = message;
          errorDiv.style.display = "block";
          showToast(message);
        }

        function clearError(fieldName) {
          const errorDiv = document.getElementById("error-" + fieldName);
          errorDiv.textContent = "";
          errorDiv.style.display = "none";
        }

        function showToast(message) {
          const toast = document.getElementById("toast");
          toast.textContent = message;
          toast.classList.remove("hidden");
          setTimeout(() => {
            toast.classList.add("hidden");
          }, 3000);
        }

        emailInput.addEventListener("input", function () {
          const email = emailInput.value;

          if (email.length > 3) {
            fetch(`/users/check-email/?email=${email}`)
              .then((response) => response.json())
              .then((data) => {
                if (data.error) {
                  showError("email", data.error);
                } else {
                  clearError("email");
                }
              })
              .catch((error) => console.error("Ошибка:", error));
          }
        });

        password1.addEventListener("input", function () {
          if (password1.value.length < 8) {
            showError("password", "Password must be at least 8 characters.");
          } else if (!/\d/.test(password1.value)) {
            showError("password", "Password must contain at least one number.");
          } else {
            clearError("password");
          }
        });

        password2.addEventListener("input", function () {
          if (password2.value !== password1.value) {
            showError("password2", "Passwords do not match.");
          } else {
            clearError("password2");
          }
        });

        form.addEventListener("submit", function (event) {
          if (
            password1.value.length < 8 ||
            !/\d/.test(password1.value) ||
            password2.value !== password1.value
          ) {
            event.preventDefault();
          }
        });
      });
    </script>
  </body>
</html>

users/templates/user_details.html
{% load static %}

<!DOCTYPE html>
<html lang="ru">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>User Details Page</title>
    <link rel="stylesheet" href="{% static 'css/user_details.css' %}" />
    <link
      href="https://fonts.googleapis.com/css2?family=Baloo&display=swap"
      rel="stylesheet"
    />
  </head>

  <body>
    <div class="page-container">
      <div class="form-container">
        <h1>Fill out your details to get <br />your personalized plan</h1>
        <form method="post" enctype="multipart/form-data">
          {% csrf_token %} {% for field in form %}
          <div class="form-field">
            {{ field.label_tag }} {{ field }} {% if field.errors %}
            <div class="error-messages">
              {% for error in field.errors %}
              <p>{{ error }}</p>
              {% endfor %}
            </div>
            {% endif %}
          </div>
          {% endfor %}
          <button type="submit" class="save-button">Save</button>
        </form>
      </div>
    </div>
  </body>
</html>